name: google-graph
version: 0.1.0.0
license: BSD3
author: "Bart Frenk"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - haxl
  - mtl
  - containers

library:
  source-dirs: src

executables:
  google-graph-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - google-graph

tests:
  google-graph-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - google-graph
