name: zeta
version: 0.1.0.0
github: "bartfrenk/zeta"
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2019 Bart Frenk"

extra-source-files:
  - README.md
  - ChangeLog.md

description: |
  Please see the README on GitHub at <https://github.com/bartfrenk/zeta#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - mtl
  # TODO: Move to zeta-test
  - hspec
  - QuickCheck

default-extensions:
  - ConstraintKinds
  - FlexibleContexts
  - LambdaCase
  - BangPatterns
  - MultiWayIf
  - RecordWildCards
  - NamedFieldPuns
  - DeriveFunctor
  - TupleSections
  - FlexibleInstances
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - BangPatterns
  - OverloadedLists
  - StandaloneDeriving
  - TypeFamilies
  - StrictData
  - GADTs
  - DeriveGeneric
  - MultiParamTypeClasses

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
    - parsec
    - indents
    - microlens-platform
    - microlens-th
    - microlens-mtl
    - microlens
    - haxl
    - hashable
    - transformers

executables:
  zeta-repl:
    main: Main.hs
    source-dirs: app/repl
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zeta

tests:
  zeta-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - zeta
