name: haskell-misc
version: 0.1.0.0
license: BSD3
author: "Bart Frenk"
maintainer: "bart.frenk@gmail.com"
copyright: "2018 Bart Frenk"

extra-source-files:
- README.md

description: >-
  Please see the README on GitHub at
  <https://github.com/githubuser/the-essence-of-dataflow-programming#readme>

dependencies:
- base >= 4.7 && < 5
- free
- bytestring
- mtl
- random
- cryptonite
- binary
- memory
- safe
- containers
- hspec
- primitive
- vector

ghc-options:
  - -Wall

library:
  source-dirs: src
