name: advent2018
version: 0.1.0.0
github: "bartfrenk/advent-of-code-e2018"
license: BSD3
author: "Bart Frenk"

description: >-
  Please see the README on GitHub at
  <https://github.com/githubuser/advent-of-code-e2018#readme>

default-extensions:
  - ConstraintKinds
  - FlexibleContexts
  - LambdaCase
  - BangPatterns
  - MultiWayIf
  - RecordWildCards
  - NamedFieldPuns
  - DeriveFunctor
  - TupleSections

dependencies:
- base >= 4.7 && < 5
- text
- parsec
- mtl
- containers
- time
- vector
- strict

library:
  source-dirs: src

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  day12:
    main: Main.hs
    source-dirs: app/day12
  day13:
    main: Main.hs
    source-dirs: app/day15
  day15:
    main: Main.hs
    source-dirs: app/day15
  day16:
    main: Main.hs
    source-dirs: app/day16

tests:
  advent-of-code-e2018-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-e2018
