name: advent2018
version: 0.1.0.0
author: "Bart Frenk"

description: >-
  Solutions to Advent of Code 2018

default-extensions:
  - ConstraintKinds
  - FlexibleContexts
  - LambdaCase
  - BangPatterns
  - MultiWayIf
  - RecordWildCards
  - NamedFieldPuns
  - DeriveFunctor
  - TupleSections
  - FlexibleInstances

dependencies:
  - base >= 4.7 && < 5
  - text
  - parsec
  - mtl
  - containers
  - time
  - vector
  - strict
  - primitive

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  day01:
    main: Main.hs
    source-dirs: src/day01
    ghc-options: *exe-ghc-options
  day02:
    main: Main.hs
    source-dirs: src/day02
    ghc-options: *exe-ghc-options
  day03:
    main: Main.hs
    source-dirs: src/day03
    ghc-options: *exe-ghc-options
  day12:
    main: Main.hs
    source-dirs: src/day12
    ghc-options: *exe-ghc-options
  day13:
    main: Main.hs
    source-dirs: src/day15
    ghc-options: *exe-ghc-options
  day15:
    main: Main.hs
    source-dirs: src/day15
    ghc-options: *exe-ghc-options
  day16:
    main: Main.hs
    source-dirs: src/day16
    ghc-options: *exe-ghc-options
  day17:
    main: Main.hs
    source-dirs: src/day17
    ghc-options: *exe-ghc-options
