name: python-from-haskell
version: 0.1.0.0
github: "githubuser/python-from-haskell"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

description: |
  Please see the README on GitHub at
  <https://github.com/githubuser/python-from-haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - cpython

library:
  source-dirs: src

executables:
  python-from-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - python-from-haskell

tests:
  python-from-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - python-from-haskell
