name: scraping
version: 0.1.0.0
license: BSD3
author: "Bart Frenk"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - haxl
  - mtl
  - containers
  - conduit
  - resourcet
  - text
  # HTTP client libraries
  - http-client-tls
  - http-client
  - http-conduit
  # Parsing XML and HTML
  - xml-conduit
  - html-conduit
  - taggy
  # Lenses
  - taggy-lens
  - xml-html-conduit-lens

default-extensions:
  - ConstraintKinds
  - FlexibleContexts
  - LambdaCase
  - BangPatterns
  - MultiWayIf
  - RecordWildCards
  - NamedFieldPuns
  - DeriveFunctor
  - TupleSections
  - FlexibleInstances
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - BangPatterns
  - OverloadedLists

library:
  source-dirs: src

executables:
  scraping-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - scraping

tests:
  scraping-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - scraping
