name: bitcoin
version: 0.1.0.0
license: BSD3

extra-source-files:
- README.md

description: |
  Please see the README on GitHub at
  <https://github.com/githubuser/bitcoin#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - random
  - cryptonite
  - binary
  - memory
  - safe
  - containers
  - hspec
  - hspec-core
  - QuickCheck
  - bytestring

ghc-options:
  - -Wall

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

default-extensions:
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - RecordWildCards

library:
  source-dirs: src

executables:
  bitcoin:
    main: Main.hs
    source-dirs: app
    ghc-options: *exe-ghc-options
    dependencies:
    - bitcoin

tests:
  bitcoin-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: *exe-ghc-options
    dependencies:
    - bitcoin
